// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArJeBRl3ANd67HCP6vGqTAxfuZxbZeCag',
    appId: '1:427101049171:web:80d79a19c36ef5739691a6',
    messagingSenderId: '427101049171',
    projectId: 'applicationapp-27ce4',
    authDomain: 'applicationapp-27ce4.firebaseapp.com',
    storageBucket: 'applicationapp-27ce4.appspot.com',
    measurementId: 'G-G80KQVTSLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkpq9fZWcXJhnM3KsyHkQVl3DO7ywhok4',
    appId: '1:427101049171:android:29b5b5eca48626cb9691a6',
    messagingSenderId: '427101049171',
    projectId: 'applicationapp-27ce4',
    storageBucket: 'applicationapp-27ce4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHrhRfZY1rGgYwBRG7A3JHBYHp33H4KN8',
    appId: '1:427101049171:ios:57139c771b4932d09691a6',
    messagingSenderId: '427101049171',
    projectId: 'applicationapp-27ce4',
    storageBucket: 'applicationapp-27ce4.appspot.com',
    iosBundleId: 'com.example.testAppdp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHrhRfZY1rGgYwBRG7A3JHBYHp33H4KN8',
    appId: '1:427101049171:ios:57139c771b4932d09691a6',
    messagingSenderId: '427101049171',
    projectId: 'applicationapp-27ce4',
    storageBucket: 'applicationapp-27ce4.appspot.com',
    iosBundleId: 'com.example.testAppdp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArJeBRl3ANd67HCP6vGqTAxfuZxbZeCag',
    appId: '1:427101049171:web:bb851fa75bcec0869691a6',
    messagingSenderId: '427101049171',
    projectId: 'applicationapp-27ce4',
    authDomain: 'applicationapp-27ce4.firebaseapp.com',
    storageBucket: 'applicationapp-27ce4.appspot.com',
    measurementId: 'G-HTPRQ7XN13',
  );
}
